FlagpoleCRM/Controllers/CampaignController.cs
using Common.Constant;
using Common.Enums;
using Common.Extension;
using Common.Helper;
using Common.Models;
using FlagpoleCRM.DTO;
using FlagpoleCRM.Helper;
using FlagpoleCRM.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace FlagpoleCRM.Controllers
{
    public class CampaignController : Controller
    {
        private readonly ILogger<CampaignController> _logger;
        private readonly IConfiguration _configuration;
        private readonly string _apiUrl;
        private readonly string _superHeaderName;
        private readonly string _superHeaderValue;

        public CampaignController(ILogger<CampaignController> logger, IConfiguration configuration)
        {
            _logger = logger;
            _configuration = configuration;
            _apiUrl = _configuration["APIUrl"];
            _superHeaderName = _configuration["SuperHeader:Name"];
            _superHeaderValue = _configuration["SuperHeader:Value"];
        }
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Request.Cookies.ContainsKey(CookiesName.JWT_COOKIE))
            {
                var token = HttpContext.Request.Cookies[CookiesName.JWT_COOKIE];
                var validateJwt = JwtHelper.ValidateToken(token, _configuration);
                if (!validateJwt.IsSuccessful)
                {
                    return Redirect("/login/authentication/index");
                }

                var userInfo = JsonConvert.DeserializeObject<JwtModel>(JsonConvert.SerializeObject(validateJwt.Data));
                TempData["email"] = userInfo.Email;
                TempData["id"] = userInfo.Id;

                var param = $"email={userInfo.Email}";
                var findAcc = await APIHelper.SearchTemplateAsync($"/api/AccountAPI/GetAccountByEmail?{param}", _apiUrl, _superHeaderName, _superHeaderValue);
                var currentAcc = JsonConvert.DeserializeObject<Account>(JsonConvert.SerializeObject(findAcc));
                TempData["avatar"] = currentAcc.Avatar;
                TempData["fullName"] = currentAcc.FullName;
                TempData["timezone"] = currentAcc.Timezone;

                var prm = $"accountId={userInfo.Id}";
                var websitesObj = await APIHelper.SearchTemplateAsync($"/api/WebsiteAPI/GetListWebsites?{prm}", _apiUrl, _superHeaderName, _superHeaderValue);
                var websites = JsonConvert.DeserializeObject<List<Website>>(JsonConvert.SerializeObject(websitesObj));
                if (websites.Count == 0)
                {
                    return Redirect("/website/index");
                }
                ViewBag.WebsiteCount = websites.Count;
                return View();
            }
            else
            {
                return Redirect("/login/authentication/index");
            }
        }

        public async Task<ResponseModel> GetEmailSenderById(int id)
        {
            try
            {
                var param = $"id={id}";
                var res = await APIHelper.SearchTemplateAsync($"/api/CampaignAPI/GetEmailSenderById?{param}", _apiUrl, _superHeaderName, _superHeaderValue);
                if (res == null)
                {
                    throw new Exception("Email sender not found");
                }
                return new ResponseModel
                {
                    IsSuccessful = true,
                    Data = JsonConvert.DeserializeObject<EmailAccount>(JsonConvert.SerializeObject(res))
                };
            }
            catch(Exception ex)
            {
                _logger.LogError($"Error when trying to get Email Sender Id = {id}: {ex.Message}");
                return new ResponseModel
                {
                    IsSuccessful = false,
                    Message = ex.Message
                };
            }
        }

        public async Task<List<EmailAccount>> GetListEmailSender(string accountId, string timezone, string websiteId)
        {
            try
            {
                var prms = $"websiteId={websiteId}";
                var res = await APIHelper.SearchTemplateAsync($"/api/CampaignAPI/GetListEmailSender?{prms}", _apiUrl, _superHeaderName, _superHeaderValue);
                if (res == null)
                {
                    return new List<EmailAccount>();
                }
                var emailSenders = JsonConvert.DeserializeObject<List<EmailAccount>>(JsonConvert.SerializeObject(res));
                foreach(EmailAccount emailSender in emailSenders)
                {
                    emailSender.CreatedDate = emailSender.CreatedDate.Value.GetTimeWithOffset(timezone);
                }
                return emailSenders;
            }
            catch(Exception ex)
            {
                _logger.LogError($"Error when trying to get list Email Senders of accountId = {accountId}: {ex.Message}");
                return new List<EmailAccount>();
            }
        }

        public async Task<ResponseModel> UpdateEmailSender(EmailAccount model)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(model.Email) || string.IsNullOrWhiteSpace(model.Password))
                {
                    return new ResponseModel { IsSuccessful = false, Message = "Email or password cannot be left blank" };
                }
                var res = await APIHelper.PostTemplateAsync(model, $"/api/CampaignAPI/UpdateEmailSender", _apiUrl, _superHeaderName, _superHeaderValue);
                var response = JsonConvert.DeserializeObject<ResponseModel>(JsonConvert.SerializeObject(res));
                if (!response.IsSuccessful)
                {
                    throw new Exception(response.Message);
                }
                return response;
            }
            catch(Exception ex)
            {
                _logger.LogError($"Error when trying to update EmaiSender Id = {model.Id}, WebsiteId = {model.WebsiteId}: {ex.Message}");
                return new ResponseModel
                {
                    IsSuccessful = false,
                    Message = "Some errors occurred"
                };
            }
            
        }

        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public ActionResult LoadManageEmailSenders(string accountId, string websiteId, string timezone)
        {
            var model = new
            {
                AccountId = accountId,
                WebsiteId = websiteId,
                Timezone = timezone
            };
            return PartialView("/Views/Shared/Campaign/_CampaignManageSenders.cshtml", model);
        }

        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public ActionResult LoadModifyCampaignView(CampaignDTO campaign)
        {
            if (campaign.SendDate.HasValue)
            {
                campaign.SendDate = campaign.SendDate.Value.GetTimeWithOffset(campaign.Timezone);
                campaign.SendDateAtInput = campaign.SendDate.Value.ToString("yyyy-MM-ddTHH:mm");
            }
            return PartialView("/Views/Shared/Campaign/_CampaignModify.cshtml", campaign);
        }

        public async Task<List<Campaign>> GetListCampaign(string timezone, string websiteId)
        {
            var prms = $"websiteId={websiteId}";
            var res = await APIHelper.SearchTemplateAsync($"/api/CampaignAPI/GetListCampaign?{prms}", _apiUrl, _superHeaderName, _superHeaderValue);
            if (res == null)
            {
                return new List<Campaign>();
            }
            var campaigns = JsonConvert.DeserializeObject<List<Campaign>>(JsonConvert.SerializeObject(res));
            foreach (Campaign campaign in campaigns)
            {
                campaign.CreatedDate = campaign.CreatedDate.GetTimeWithOffset(timezone);
                campaign.ModifiedDate = campaign.ModifiedDate.HasValue 
                    ? campaign.ModifiedDate.Value.GetTimeWithOffset(timezone)
                    : null;
                campaign.SendDate = campaign.SendDate.Value.GetTimeWithOffset(timezone);
            }
            return campaigns;
        }

        public async Task<ResponseModel> GetCampaignById(int id)
        {
            try
            {
                var param = $"id={id}";
                var res = await APIHelper.SearchTemplateAsync($"/api/CampaignAPI/GetCampaignById?{param}", _apiUrl, _superHeaderName, _superHeaderValue);
                if (res == null)
                {
                    throw new Exception("Campaign not found");
                }
                return new ResponseModel
                {
                    IsSuccessful = true,
                    Data = JsonConvert.DeserializeObject<Campaign>(JsonConvert.SerializeObject(res))
                };
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error when trying to get Campaign Id = {id}: {ex.Message}");
                return new ResponseModel
                {
                    IsSuccessful = false,
                    Message = ex.Message
                };
            }
        }

        public async Task<ResponseModel> UpdateCampaign(CampaignDTO model)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(model.Name) || string.IsNullOrWhiteSpace(model.SenderName))
                {
                    return new ResponseModel { IsSuccessful = false, Message = "Required fields cannot be left blank" };
                }

                if (model.SendType == (int)ESendType.Scheduled && model.SendDate.Value.Subtract(DateTime.Now).TotalMinutes < 30)
                {
                    return new ResponseModel { IsSuccessful = false, Message = "Scheduled date must be at least 30 minutes later from now" };
                }

                var getWebsiteParam = $"id={model.WebsiteGuid}";

FlagpoleCRM/Controllers/TemplateBuilderController.cs
using Common.Constant;
using Common.Extension;
using Common.Helper;
using Common.Models;
using FlagpoleCRM.DTO;
using FlagpoleCRM.Helper;
using FlagpoleCRM.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Newtonsoft.Json;

namespace FlagpoleCRM.Controllers
{
    public class TemplateBuilderController : Controller
    {
        private readonly ILogger<TemplateBuilderController> _logger;
        private readonly IConfiguration _configuration;
        private readonly string _apiUrl;
        private readonly string _superHeaderName;
        private readonly string _superHeaderValue;

        public TemplateBuilderController(ILogger<TemplateBuilderController> logger, IConfiguration configuration)
        {
            _logger = logger;
            _configuration = configuration;
            _apiUrl = _configuration["APIUrl"];
            _superHeaderName = _configuration["SuperHeader:Name"];
            _superHeaderValue = _configuration["SuperHeader:Value"];
        }
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Request.Cookies.ContainsKey(CookiesName.JWT_COOKIE))
            {
                var token = HttpContext.Request.Cookies[CookiesName.JWT_COOKIE];
                var validateJwt = JwtHelper.ValidateToken(token, _configuration);
                if (!validateJwt.IsSuccessful)
                {
                    return Redirect("/login/authentication/index");
                }

                var userInfo = JsonConvert.DeserializeObject<JwtModel>(JsonConvert.SerializeObject(validateJwt.Data));
                TempData["email"] = userInfo.Email;
                TempData["id"] = userInfo.Id;

                var param = $"email={userInfo.Email}";
                var findAcc = await APIHelper.SearchTemplateAsync($"/api/AccountAPI/GetAccountByEmail?{param}", _apiUrl, _superHeaderName, _superHeaderValue);
                var currentAcc = JsonConvert.DeserializeObject<Account>(JsonConvert.SerializeObject(findAcc));
                TempData["avatar"] = currentAcc.Avatar;
                TempData["fullName"] = currentAcc.FullName;

                var prm = $"accountId={userInfo.Id}";
                var websitesObj = await APIHelper.SearchTemplateAsync($"/api/WebsiteAPI/GetListWebsites?{prm}", _apiUrl, _superHeaderName, _superHeaderValue);
                var websites = JsonConvert.DeserializeObject<List<Website>>(JsonConvert.SerializeObject(websitesObj));
                if (websites.Count == 0)
                {
                    return Redirect("/website/index");
                }
                ViewBag.WebsiteCount = websites.Count;
                return View();
            }
            else
            {
                return Redirect("/login/authentication/index");
            }
        }

        public async Task<List<Template>> GetTemplates(string websiteId, string email)
        {
            try
            {
                var param = $"email={email}";
                var findAcc = await APIHelper.SearchTemplateAsync($"/api/AccountAPI/GetAccountByEmail?{param}", _apiUrl, _superHeaderName, _superHeaderValue);
                if (findAcc == null)
                {
                    throw new Exception("Current account not found");
                }
                var acc = JsonConvert.DeserializeObject<Account>(JsonConvert.SerializeObject(findAcc));
                var timezone = acc.Timezone;

                var prms = $"websiteId={websiteId}";
                var templatesObj = await APIHelper.SearchTemplateAsync($"/api/TemplateBuilderAPI/GetTemplates?{prms}", _apiUrl, _superHeaderName, _superHeaderValue);
                var templates = JsonConvert.DeserializeObject<List<Template>>(JsonConvert.SerializeObject(templatesObj));

                foreach(Template template in templates)
                {
                    template.CreatedDate = template.CreatedDate.GetTimeWithOffset(timezone);
                }
                return templates;
            }
            catch (Exception e)
            {
                _logger.LogError($"Get templates of websiteId = {websiteId} failed: {e.Message}");
                return new List<Template>();
            }
        }

        public async Task<ResponseModel> GetTemplateById(int id)
        {
            try
            {
                var prms = $"id={id}";
                var templateObj = await APIHelper.SearchTemplateAsync($"/api/TemplateBuilderAPI/GetTemplateById?{prms}", _apiUrl, _superHeaderName, _superHeaderValue);
                if (templateObj == null)
                {
                    throw new Exception("Template not found");
                }
                var template = JsonConvert.DeserializeObject<Template>(JsonConvert.SerializeObject(templateObj));
                return new ResponseModel
                {
                    IsSuccessful = true,
                    Data = template
                };
            }
            catch(Exception ex)
            {
                _logger.LogError($"Error when trying to get template with id = {id}: {ex.Message}");
                return new ResponseModel
                {
                    IsSuccessful = false,
                    Message = "Some errors occurred"
                };
            }
        }

        public async Task<ResponseModel> InsertOrUpdate(Template template)
        {
            var response = new ResponseModel { IsSuccessful = true };
            try
            {
                if (string.IsNullOrWhiteSpace(template.Name))
                {
                    throw new Exception("Name is not set yet");
                }

                var prms = $"id={template.WebsiteGuid}";
                var findWebsite = await APIHelper.SearchTemplateAsync($"/api/WebsiteAPI/GetWebsiteById?{prms}", _apiUrl, _superHeaderName, _superHeaderValue);
                if (findWebsite == null)
                {
                    throw new Exception("Current website not found");
                }
                template.WebsiteId = JsonConvert.DeserializeObject<Website>(JsonConvert.SerializeObject(findWebsite)).Id;

                var resInsert = (ResponseModel)await APIHelper.PostTemplateAsync(template, $"/api/TemplateBuilderAPI/InsertOrUpdate", _apiUrl, _superHeaderName, _superHeaderValue);
                if (!resInsert.IsSuccessful)
                {
                    throw new Exception("Some error occurred");
                }
            }
            catch(Exception ex)
            {
                _logger.LogError($"Error when trying to insert/update template: TemplateId = {template.Id}, WebsiteId = {template.WebsiteGuid}: {ex.Message}");
                response.IsSuccessful = false;
                response.Message = ex.Message;
            }
            return response;
        }
    }
}

FlagpoleCRM/Views/Shared/Campaign/_CampaignModify.cshtml
@using Common.Enums
@using FlagpoleCRM.DTO
@model CampaignDTO

<style>
    .campaign-input {
        width: 35%;
        padding-right: 20px;
        border-right: 1px #5c5c5c solid;
    }

    #campaign-preview {
        width: 65%;
        margin-left: 20px;
        padding-left: 20px;
        background-color: white;
        color: #333;
        max-height: 550px;
        overflow-y: scroll;
        overflow-x: scroll;
    }

    .campaign-label {
        margin-top: 5px;
    }
</style>

<div class="modal fade" id="add-campaign-modal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" style="max-width: 1200px">
        <div class="modal-content">
            <div class="modal-header">
                @if (Model.Id == 0) {
                    <h5 class="modal-title">Add campaign</h5>
                }
                else {
                    <h5 class="modal-title">Edit campaign</h5>
                }
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div style="display:flex">
                    <div class="campaign-input">
                        <input type="text" id="campaign-id" value="@Model.Id" hidden/>
                        <label>Name <span class="mark-required-field">*</span></label>
                        <input type="text" class="form-control" id="campaign-name" value="@Model.Name"/>
                        <label class="campaign-label">Description</label>
                        <input type="text" class="form-control" id="campaign-description" value="@Model.Description"/>
                        <label class="campaign-label">Recipients</label>
                        <select class="form-control" id="campaign-recipients"></select>
                        <label class="campaign-label">Sender</label>
                        <select class="form-control" id="campaign-sender"></select>
                        <label class="campaign-label">Sender name <span class="mark-required-field">*</span></label>
                        <input type="text" class="form-control" id="campaign-sender-name" value="@Model.SenderName">
                        <label class="campaign-label">Template</label>
                        <select class="form-control" id="campaign-template"></select>
                        <label class="campaign-label">Schedule</label><br>
                        @if (Model.SendType == (int)ESendType.Immediate) {
                            <input type="radio" id="send-now" name="campaign-schedule" value="0" checked>
                            <label for="send-now">Send now</label>
                            <br>
                            <input type="radio" id="send-then" name="campaign-schedule" value="1" >
                            <label for="send-then">Send at</label>
                            <br />
                            <input type="datetime-local" class="form-control" style="color-scheme: dark" id="campaign-send-date" hidden>
                        }
                        else {
                            <input type="radio" id="send-now" name="campaign-schedule" value="0" >
                            <label for="send-now">Send now</label>
                            <br>
                            <input type="radio" id="send-then" name="campaign-schedule" value="1" checked>
                            <label for="send-then">Send at</label>
                            <br />
                            <input type="datetime-local" class="form-control" style="color-scheme: dark" id="campaign-send-date" value="@Model.SendDateAtInput">
                        }
                        
                        @if (Model.SendStatus != (int)ESendStatus.Sending && Model.SendStatus != (int)ESendStatus.Complete) {
                            <a class="btn btn-primary mt-3" id="save-campaign">Save campaign</a>
                        }
                    </div>
                    <div id="campaign-preview"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        getAudiences();
        getTemplates();
        getListEmailSender();
    })

    function getAudiences() {
        $.ajax({
            url: `@Url.Action("GetAudiences", "Customer")?websiteId=@Model.WebsiteGuid`,
            type: 'get',
            success: (result) => {
                $('#campaign-recipients').html('');
                result.forEach((value, index) => {
                    var attr = '';
                    if ('@Model.AudienceId' == value.id) {
                        attr = 'selected';
                    }
                    else {
                        attr = '';
                    }
                    $('#campaign-recipients').append(`<option value="${value.id}" ${attr}>${value.name}</option>`);
                });
            }
        });
    }
    
    function getTemplates() {
        $.ajax({
            url: `@Url.Action("GetTemplates", "TemplateBuilder")?websiteId=@Model.WebsiteGuid&email=@Model.AccountEmail`,
            type: 'get',
            success: (result) => {
                $('#campaign-template').html('');
                var templateId = 0;
                result.forEach((value, index) => {
                    var attr = '';
                    if ('@Model.TemplateId' == value.id) {
                        attr = 'selected';
                        templateId = value.id;
                    }
                    else {
                        attr = '';
                    }
                    $('#campaign-template').append(`<option value="${value.id}" ${attr}>${value.name}</option>`);
                });
                if (templateId != 0) {
                    showTemplatePreview(templateId);
                }
                else {
                    showTemplatePreview($('#campaign-template').find(":selected").val());
                }
            }
        });
    }

    function getListEmailSender() {
        $.ajax({
            url: `@Url.Action("GetListEmailSender", "Campaign")?accountId=@Model.AccountId&websiteId=@Model.WebsiteGuid`,
            type: 'get',
            success: (result) => {
                $('#campaign-sender').html('');
                result.forEach((value, index) => {
                    var attr = '';
                    if ('@Model.EmailId' == value.id) {
                        attr = 'selected';
                    }
                    else {
                        attr = '';
                    }
                    $('#campaign-sender').append(`<option value="${value.id}" ${attr}>${value.email}</option>`);
                });
            }
        });
    }

    function showTemplatePreview(id) {
        $.ajax({
            url: `@Url.Action("GetTemplateById", "TemplateBuilder")?id=${id}`,
            type: 'get',
            success: (result) => {
                if (!result.isSuccessful) {
                    toastr_call('error', 'Error', 'Could not load template');
                }
                else {
                    var template = result.data;
                    $('#campaign-preview').html(template.content);
                }
            }
        })
    }

    $('#save-campaign').click(function() {
        var id = $('#campaign-id').val();
        var name = $('#campaign-name').val();
        var description = $('#campaign-description').val();
        var audienceId = $('#campaign-recipients').find(":selected").val();
        var templateId = $('#campaign-template').find(":selected").val();
        var emailId = $('#campaign-sender').find(":selected").val();
        var senderName = $('#campaign-sender-name').val();
        var accountId = '@Model.AccountId';
        var sendType = $('input[name=campaign-schedule]:checked').val();
        var sendDate = sendType == 0 ? getDateTimeFromDateObj(new Date()) : $('#campaign-send-date').val();
        var channel = @((int)EChannelSubscribe.Email);
        var websiteGuid = '@Model.WebsiteGuid';
        var timezone = '@Html.Raw(Model.Timezone)';

        if (!name || !senderName) {
            toastr_call('error', 'Error', 'Required fields cannot be left blank');
        }
        else {
            $.ajax({
                url: `@Url.Action("UpdateCampaign", "Campaign")`,
                type: 'post',
                data: { id, name, description, audienceId, templateId, emailId, senderName, accountId, sendType, sendDate, channel, websiteGuid, timezone },
                success: (result) => {
                    if (!result.isSuccessful) {
                        toastr_call('error', 'Error', result.message);
                    }
                    else {
                        toastr_call('success', 'Success', 'Update campaign successfully');
                        loadCampaigns();
                    }
                }
            });
        }
    });

    $('#campaign-template').change(function() {
        showTemplatePreview(this.value);
    })

    $('input[name=campaign-schedule]').change(function() {
        if (this.value == 0) {
            $('#campaign-send-date').attr('hidden', true);
        }
        else {
            $('#campaign-send-date').attr('hidden', false);
        }
    })
</script>