FlagpoleCRM/Controllers/WebsiteController.cs
using Common.Constant;
using Common.Extension;
using Common.Helper;
using Common.Models;
using FlagpoleCRM.DTO;
using FlagpoleCRM.Helper;
using FlagpoleCRM.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Newtonsoft.Json;

namespace FlagpoleCRM.Controllers
{
    public class WebsiteController : Controller
    {
        private readonly ILogger<WebsiteController> _logger;
        private readonly IConfiguration _configuration;
        private readonly string _apiUrl;
        private readonly string _superHeaderName;
        private readonly string _superHeaderValue;

        public WebsiteController(ILogger<WebsiteController> logger, IConfiguration configuration)
        {
            _logger = logger;
            _configuration = configuration;
            _apiUrl = _configuration["APIUrl"];
            _superHeaderName = _configuration["SuperHeader:Name"];
            _superHeaderValue = _configuration["SuperHeader:Value"];
        }
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Request.Cookies.ContainsKey(CookiesName.JWT_COOKIE))
            {
                var token = HttpContext.Request.Cookies[CookiesName.JWT_COOKIE];
                var validateJwt = JwtHelper.ValidateToken(token, _configuration);
                if (!validateJwt.IsSuccessful)
                {
                    return Redirect("/login/authentication/index");
                }

                var userInfo = JsonConvert.DeserializeObject<JwtModel>(JsonConvert.SerializeObject(validateJwt.Data));
                TempData["email"] = userInfo.Email;
                TempData["id"] = userInfo.Id;

                var param = $"email={userInfo.Email}";
                var findAcc = await APIHelper.SearchTemplateAsync($"/api/AccountAPI/GetAccountByEmail?{param}", _apiUrl, _superHeaderName, _superHeaderValue);
                var currentAcc = JsonConvert.DeserializeObject<Account>(JsonConvert.SerializeObject(findAcc));
                TempData["avatar"] = currentAcc.Avatar;
                TempData["fullName"] = currentAcc.FullName;

                var websites = GetWebsites(userInfo.Id).Result;
                ViewBag.WebsiteCount = websites.Count;

                return View();
            }
            else
            {
                return Redirect("/login/authentication/index");
            }
        }

        public async Task<ResponseModel> CreateWebsite(string name, string accountId)
        {
            try
            {
                var website = new Website() { Guid = "", Url = name, AccountId = accountId };
                var response = (ResponseModel)await APIHelper.PostTemplateAsync(website, "/api/WebsiteAPI/CreateWebsite", _apiUrl, _superHeaderName, _superHeaderValue);
                if (!response.IsSuccessful)
                {
                    throw new Exception(response.Message);
                }
                return response;
            }
            catch(Exception ex)
            {
                _logger.LogError($"Create website name = {name}, accountId = {accountId} failed: {ex.Message}");
                return new ResponseModel { IsSuccessful = false, Message = "Some errors occurred" };
            }
        }

        public async Task<List<WebsiteDTO>> GetWebsites(string accountId)
        {
            try
            {
                var getAccountParam = $"id={accountId}";
                var findAcc = await APIHelper.SearchTemplateAsync($"/api/AccountAPI/GetAccountById?{getAccountParam}", _apiUrl, _superHeaderName, _superHeaderValue);
                if (findAcc == null)
                {
                    throw new Exception("Current account not found");
                }
                var acc = JsonConvert.DeserializeObject<Account>(JsonConvert.SerializeObject(findAcc));
                var timezone = acc.Timezone;

                var prms = $"accountId={accountId}";
                var websitesObj = await APIHelper.SearchTemplateAsync($"/api/WebsiteAPI/GetListWebsites?{prms}", _apiUrl, _superHeaderName, _superHeaderValue);

                var websites = JsonConvert.DeserializeObject<List<WebsiteDTO>>(JsonConvert.SerializeObject(websitesObj));
                foreach(Website website in websites)
                {
                    website.CreatedDate = website.CreatedDate.GetTimeWithOffset(timezone);
                }
                return websites;
            }
            catch(Exception e)
            {
                _logger.LogError($"Get website of accountId = {accountId} failed: {e.Message}");
                return new List<WebsiteDTO>();
            }
        }
    }
}

FlagpoleCRM/Views/Shared/_CustomerSaveAudience.cshtml
@using FlagpoleCRM.Models
@model Audience
@{
    var warning = "By choosing this option, you agree that the customers which are displayed in this audience can be different from actual data";
}

<style>
    .mark-required-field {
        color: #EE9EA5;
    }

    #static-warning {
        color: #F1E50E;
    }
</style>

<input type="hidden" id="audience-id" value="@Model.Id"/>
<label>Audience name <span class="mark-required-field">*</span></label>
<input type="text" class="form-control mb-2" id="audience-name" value="@Model.Name" />
<label>Description</label>
<input type="text" class="form-control mb-2" id="audience-description" value="@Model.Description" />
<label>Audience type <span class="mark-required-field">*</span></label>
<div>
    @if (Model.IsDynamic) {
        <input type="radio" name="audience-type" value="1" id="dynamic" checked/>
        <label for="dynamic">Dynamic</label>
        <br />
        <input type="radio" name="audience-type" value="0" id="static" />
        <label for="static">Static</label>
        <br />
        <span id="static-warning"></span>   
    }
    else {
        <input type="radio" name="audience-type" value="1" id="dynamic" />
        <label for="dynamic">Dynamic</label>
        <br />
        <input type="radio" name="audience-type" value="0" id="static" checked/>
        <label for="static">Static</label>
        <br />
        <span id="static-warning">@warning</span>
    }
</div>
<label class="mt-2">Limit <span class="mark-required-field">*</span></label>
<input type="number" class="form-control" id="audience-limit" value="@Model.Limit" />
<span><i>Value "0" means there is no limit</i></span>

<script>
    $('input[name="audience-type"]').change(function () {
        displayWarning(this.value);
    });
    function displayWarning(value) {
        $('#static-warning').html('');
        if (value == 0) {
            $('#static-warning').html('@warning');
        }
    }
</script>

FlagpoleCRM/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en" class="dark-theme">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="/img/brand/logo-333333.png" type="image/png" />
    <!-- Bootstrap CSS -->
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/assets/css/bootstrap-extended.css" rel="stylesheet" />
    <link href="/assets/css/style.css" rel="stylesheet" />
    <link href="/assets/css/icons.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <!--plugins-->
    <link href="/assets/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet" />
    <link href="/assets/plugins/queryBuilder/css/query-builder.default.css" rel="stylesheet" />
    <link href="/assets/plugins/toast/css/toastr.min.css" rel="stylesheet" />
    <link href="/assets/plugins/datatable/css/dataTables.min.css" rel="stylesheet" />
    <link href="/assets/plugins/datatable/css/dataTables.bootstrap5.min.css" rel="stylesheet" />
    <link href="/assets/plugins/fontawesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    
    <!--Theme Styles-->
    <link href="/assets/css/dark-theme.css" rel="stylesheet" />

    @await RenderSectionAsync("Css", required: false)

    <title>Flagpole CRM</title>
</head>

<body>
    <!--start wrapper-->
    <div class="wrapper">
        <!--start top header-->
        <header class="top-header">
            <nav class="navbar navbar-expand gap-3">
                <div class="mobile-toggle-icon fs-3">
                    <i class="bi bi-list"></i>
                </div>
                <div class="dropdown">
                    @if (ViewBag.WebsiteCount > 0) {
                        <select class="form-control custom-dropdown" id="choose-websites">
                        </select>
                    }
                </div>
                <div class="top-navbar-right ms-auto">
                    <ul class="navbar-nav align-items-center">
                        <li class="nav-item dropdown dropdown-user-setting">
                            <a class="nav-link dropdown-toggle dropdown-toggle-nocaret" data-bs-toggle="dropdown" href="#">
                                <div class="user-setting d-flex align-items-center">
                                    <img src="@TempData["avatar"]" class="user-img" alt="">
                                </div>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end">
                                <li>
                                    <div class="dropdown-item personal-dropdown-item">
                                        <div class="d-flex align-items-center">
                                            <img src="@TempData["avatar"]" alt="" class="rounded-circle" width="54" height="54">
                                            <div class="ms-3">
                                                <h6 class="mb-0 dropdown-user-name">@TempData["fullName"]</h6>
                                                <small class="mb-0 dropdown-user-designation text-secondary">@TempData["email"]</small>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li><hr class="dropdown-divider"></li>
                                <li>
                                    <a class="dropdown-item personal-dropdown-item" href="/profile/index">
                                        <div class="d-flex align-items-center">
                                            <div class=""><i class="bi bi-person-fill"></i></div>
                                            <div class="ms-3"><span>Profile</span></div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item personal-dropdown-item" id="logout" style="cursor:pointer">
                                        <div class="d-flex align-items-center">
                                            <div class=""><i class="bi bi-lock-fill"></i></div>
                                            <div class="ms-3"><span>Logout</span></div>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!--end top header-->
        <!--start sidebar -->
        <aside class="sidebar-wrapper" data-simplebar="true">
            <div class="sidebar-header">
                <div>
                    <img src="/img//brand/logo-white.png" class="logo-icon" alt="logo icon">
                </div>
                <div>
                    <h4 class="logo-text">Flagpole CRM</h4>
                </div>
                <div class="toggle-icon ms-auto">
                    <i class="bi bi-list"></i>
                </div>
            </div>
            <!--navigation-->
            <ul class="metismenu" id="menu">
                <li>
                    <a href="/customer/index">
                        <div class="parent-icon">
                            <i class="bi bi-people-fill"></i>
                        </div>
                        <div class="menu-title">Customers</div>
                    </a>
                </li>
                <li>
                    <a href="/templatebuilder/index">
                        <div class="parent-icon">
                            <i class="bi bi-hammer"></i>
                        </div>
                        <div class="menu-title">Template Builder</div>
                    </a>
                </li>
                <li>
                    <a href="/campaign/index">
                        <div class="parent-icon">
                            <i class="bi bi-envelope"></i>
                        </div>
                        <div class="menu-title">Campaigns</div>
                    </a>
                </li>
                <li>
                    <a href="/report/index">
                        <div class="parent-icon">
                            <i class="bi bi-newspaper"></i>
                        </div>
                        <div class="menu-title">Report</div>
                    </a>
                </li>
                <li>
                    <a href="/website/index">
                        <div class="parent-icon">
                            <i class="bi bi-globe2"></i>
                        </div>
                        <div class="menu-title">Websites</div>
                    </a>
                </li>
                <li>
                    <a href="/DataSynchronization/index">
                        <div class="parent-icon">
                            <i class="bi bi-arrow-repeat"></i>
                        </div>
                        <div class="menu-title">Data synchronization</div>
                    </a>
                </li>
            </ul>
            <!--end navigation-->
        </aside>
        <!--end sidebar -->
        <!--start content-->
        @RenderBody()
        <!--end page main-->
        <!--start overlay-->
        <div class="overlay nav-toggle-icon"></div>
        <!--end overlay-->
        <!--Start Back To Top Button-->
        <a href="javaScript:;" class="back-to-top"><i class='bx bxs-up-arrow-alt'></i></a>
        <!--End Back To Top Button-->

    </div>

    <div class="loading"></div>
    <!--end wrapper-->
    <!-- Bootstrap bundle JS -->
    <script src="/assets/js/bootstrap.bundle.min.js"></script>
    <!--plugins-->
    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/plugins/datatable/js/jquery.dataTables.min.js"></script>
    <script src="/assets/plugins/datatable/js/dataTables.bootstrap5.min.js"></script>
    <script src="/assets/plugins/bootstrap-material-datetimepicker/js/moment.min.js"></script>
    <script src="/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="/assets/plugins/queryBuilder/js/query-builder.standalone.js"></script>
    <script src="/assets/plugins/ckeditor/ckeditor.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highstock/6.0.3/highstock.js"></script>
    <script src="/assets/plugins/toast/js/toastr.min.js"></script>
    <script src="/assets/js/app.js"></script>
    <script>
        function toastr_call(type, title, msg) {
            toastr[type](msg, title);
            toastr.options = {
                "closeButton": false,
                "debug": false,
                "newestOnTop": false,
                "progressBar": true,
                "positionClass": "toast-top-right",
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "timeOut": "20000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            }
        }
    </script>
    <script>
        var currentWebsite = '@Common.Constant.CookiesName.CURRENT_WEBSITE';

        $(document).ready(function() {
            loadWebsiteMenu();
        })

        function loadWebsiteMenu() {
            $.ajax({
                type: 'get',
                url: `@Url.Action("GetWebsites", "Website")?accountId=@TempData["id"]`
            }).done(function (res) {
                $('#choose-websites').html('');
                var selectedAttr = 'selected';
                res.forEach((item, index) => {
                    if (localStorage.getItem(currentWebsite) == null || localStorage.getItem(currentWebsite) == undefined) {
                        localStorage.setItem(currentWebsite, item.guid);
                    }
                    else {
                        if (localStorage.getItem(currentWebsite) != item.guid) {
                            selectedAttr = '';
                        }
                        else {
                            selectedAttr = 'selected';
                        }
                    }

                    $('#choose-websites').append(`<option value="${item.guid}" ${selectedAttr}>${item.url}</option>`);
                })
            })
        }

        $('#choose-websites').change(function() {
            localStorage.setItem(currentWebsite, $('#choose-websites').find(":selected").val());
        })

        $('#logout').click(function() {
            $.ajax({
                url: '/login/authentication/logout',
                type: 'get',
                success: (result) => {
                    if (!result.isSuccessful) {
                        toastr_call('error', 'Error', 'Cannot log out, please try again later');
                    }
                    else {
                        localStorage.clear();
                        location.reload();
                    }
                }
            })
        })

        function convertDate(date) {
            var datePart = date.match(/\d+/g),
                year = datePart[0].substring(),
                month = datePart[1], 
                day = datePart[2];

            return day + '/' + month + '/' + year;
        }

        function convertDateTime(datetime) {
            var datePart = datetime.match(/\d+/g),
                year = datePart[0].substring(),
                month = datePart[1], 
                day = datePart[2],
                hour = datePart[3],
                minute = datePart[4];

            return day + '/' + month + '/' + year + ' ' + hour + ':' + minute;
        }

        function getDateTimeFromDateObj(dateObject) {
            var year = dateObject.getFullYear();
            var month = (dateObject.getMonth() + 1).toString().padStart(2, '0');
            var day = dateObject.getDate().toString().padStart(2, '0');
            var hours = dateObject.getHours().toString().padStart(2, '0');
            var minutes = dateObject.getMinutes().toString().padStart(2, '0');
            return `${year}-${month}-${day}T${hours}:${minutes}`;
        }
    </script>
    @await RenderSectionAsync("Script", required: false)

</body>

</html>