FlagpoleCRM/Controllers/DataSynchronizationController.cs
using Common.Constant;
using Common.Helper;
using Common.Models;
using FlagpoleCRM.Helper;
using FlagpoleCRM.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace FlagpoleCRM.Controllers
{
    public class DataSynchronizationController : Controller
    {
        private readonly ILogger<DataSynchronizationController> _logger;
        private readonly IConfiguration _configuration;
        private readonly string _apiUrl;
        private readonly string _superHeaderName;
        private readonly string _superHeaderValue;
        public DataSynchronizationController(ILogger<DataSynchronizationController> logger, IConfiguration configuration)
        {
            _logger = logger;
            _configuration = configuration;
            _apiUrl = _configuration["APIUrl"];
            _superHeaderName = _configuration["SuperHeader:Name"];
            _superHeaderValue = _configuration["SuperHeader:Value"];
        }
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Request.Cookies.ContainsKey(CookiesName.JWT_COOKIE))
            {
                var token = HttpContext.Request.Cookies[CookiesName.JWT_COOKIE];
                var validateJwt = JwtHelper.ValidateToken(token, _configuration);
                if (!validateJwt.IsSuccessful)
                {
                    return Redirect("/login/authentication/index");
                }

                var userInfo = JsonConvert.DeserializeObject<JwtModel>(JsonConvert.SerializeObject(validateJwt.Data));
                TempData["email"] = userInfo.Email;
                TempData["id"] = userInfo.Id;

                var param = $"email={userInfo.Email}";
                var findAcc = await APIHelper.SearchTemplateAsync($"/api/AccountAPI/GetAccountByEmail?{param}", _apiUrl, _superHeaderName, _superHeaderValue);
                var currentAcc = JsonConvert.DeserializeObject<Account>(JsonConvert.SerializeObject(findAcc));
                TempData["avatar"] = currentAcc.Avatar;
                TempData["fullName"] = currentAcc.FullName;

                var prm = $"accountId={userInfo.Id}";
                var websitesObj = await APIHelper.SearchTemplateAsync($"/api/WebsiteAPI/GetListWebsites?{prm}", _apiUrl, _superHeaderName, _superHeaderValue);
                var websites = JsonConvert.DeserializeObject<List<Website>>(JsonConvert.SerializeObject(websitesObj));
                if (websites.Count == 0)
                {
                    return Redirect("/website/index");
                }
                ViewBag.WebsiteCount = websites.Count;
                return View();
            }
            else
            {
                return Redirect("/login/authentication/index");
            }
        }

        public async Task<ResponseModel> SaveAccessToken(string token, string dataSource, string shopDomain, string websiteId)
        {
            var response = new ResponseModel() { IsSuccessful = true };
            if (string.IsNullOrEmpty(token))
            {
                response.IsSuccessful = false;
                response.Message = "Invalid access token";
                return response;
            }

            var website = new Website { Guid = websiteId, AccountId = "", Url = "", IsDeleted = false };
            switch(dataSource)
            {
                case DataSource.SHOPIFY:
                    if (string.IsNullOrEmpty(shopDomain))
                    {
                        response.IsSuccessful = false;
                        response.Message = "Shop domain could not be blank";
                        return response;
                    }

                    website.ShopifyStore = shopDomain;
                    website.ShopifyToken = token;
                    break;
                case DataSource.HARAVAN:
                    website.HaravanToken = token;
                    break;
                default:
                    response.IsSuccessful = false;
                    response.Message = "Internal server error";
                    return response;
            }
            response = (ResponseModel)await APIHelper.PostTemplateAsync(website, "/api/WebsiteAPI/UpdateWebsite", _apiUrl, _superHeaderName, _superHeaderValue);
            if (!response.IsSuccessful)
            {
                _logger.LogError($"Save access token failed with token = {token}, dataSource = {dataSource}, " +
                    $"shopDomain = {shopDomain}, websiteId = {websiteId}: {response.Message}");
            }
            return response;
        }

        public async Task<Website> GetWebsiteById(string id)
        {
            var prms = $"id={id}";
            var websiteObj = await APIHelper.SearchTemplateAsync($"/api/WebsiteAPI/GetWebsiteById?{prms}", _apiUrl, _superHeaderName, _superHeaderValue);
            if (websiteObj != null)
            {
                return JsonConvert.DeserializeObject<Website>(JsonConvert.SerializeObject(websiteObj));
            }
            _logger.LogError($"Website with id = {id} not found");
            return null;
        }
    }
}

FlagpoleCRM/Views/DataSynchronization/Index.cshtml
@{
    Layout = "/Views/Shared/_Layout.cshtml";
}

<style>
    .web-sync-logo {
        width: 48px;
        height: 48px;
    }
    .sync-modal {
        max-width: 1300px;
    }
    .sync-input {
        width: 40%;
        padding-right: 20px;
        border-right: 1px #5c5c5c solid;
    }
    .sync-tutorial {
        width: 60%;
        overflow-y: scroll;
        padding-left: 20px;
        max-height: 450px;
    }
    .align-text-center {
        text-align: center;
    }
    .sync-tutorial-img {
        max-height: 300px;
        margin-bottom: 20px;
    }
</style>

<main class="page-content">
    <div class="breadcrumb-title pe-3">Data Synchronization</div>
    <hr>
    <div class="row row-cols-2 row-cols-sm-3 row-cols-md-4 row-cols-xl-6 row-cols-xxl-6">
        <div class="col">
            <div class="card radius-10" style="background-color:#1B67A3">
                <div class="card-body text-center">
                    <div class="widget-icon mx-auto mb-3 bg-white-1 text-white" data-bs-toggle="modal" data-bs-target="#haravan-setting">
                        <img src="/img/other-logos/haravan-logo.jpg" class="web-sync-logo"/>
                    </div>
                    <h3 class="text-white">Haravan</h3>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card radius-10" style="background-color: #5E8D3E">
                <div class="card-body text-center">
                    <div class="widget-icon mx-auto mb-3 bg-white-1 text-white" data-bs-toggle="modal" data-bs-target="#shopify-setting">
                        <img src="/img/other-logos/shopify-logo.jpg" class="web-sync-logo" />
                    </div>
                    <h3 class="text-white">Shopify</h3>
                </div>
            </div>
        </div>
    </div><!--end row-->

    <div class="modal fade" id="haravan-setting" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered sync-modal">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Sync data from Haravan</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" style="display:flex">
                    <div class="sync-input">
                        <label>Access token:</label>
                        <input type="password" class="form-control" placeholder="Your access token" id="haravan-access-token"/>
                    </div>
                    <div class="sync-tutorial">
                        <h5 class="align-text-center">How to get <b>Access token</b>?</h5>
                        <p><b>Step 1:</b> Click on <i>Apps</i> on your sidebar and choose <i>Private apps</i></p>
                        <div class="align-text-center">
                            <img src="~/img/tutorial/haravan-tutorial/step-1.png" class="sync-tutorial-img" />
                        </div>
                        <p><b>Step 2:</b> Choose <i>Create private app</i></p>
                        <div class="align-text-center">
                            <img src="~/img/tutorial/haravan-tutorial/step-2(2).png" class="sync-tutorial-img" />
                        </div>
                        <p><b>Step 3:</b> Enter app name and grant Admin API permissions, then click <i>Create private apps</i></p>
                        <div class="align-text-center">
                            <img src="~/img/tutorial/haravan-tutorial/step-3.png" class="sync-tutorial-img" />
                        </div>
                        <p><b>Step 4:</b> Retrieve access token</p>
                        <div class="align-text-center">
                            <img src="~/img/tutorial/haravan-tutorial/step-4.png" class="sync-tutorial-img" />
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="save-haravan-setting">Save changes</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="shopify-setting" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered sync-modal">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Sync data from Shopify</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" style="display:flex">
                    <div class="sync-input">
                        <label>Access token:</label>
                        <input type="password" class="form-control" placeholder="Your access token" id="shopify-access-token"/>
                        <label style="margin-top:15px">Shop domain:</label>
                        <input type="text" class="form-control" placeholder="Your shop domain" id="shopify-shop-domain"/>
                    </div>
                    <div class="sync-tutorial">
                        <h5 class="align-text-center">How to get <b>Access token</b> and <b>Shop domain</b>?</h5>
                        <p><b>Step 1:</b> Click on <i>Apps</i> on your sidebar</p>
                        <div class="align-text-center">
                            <img src="~/img/tutorial/shopify-tutorial/click-on-apps.png" class="sync-tutorial-img"/>
                        </div>
                        <p><b>Step 2:</b> Choose <i>App and sales channel settings</i></p>
                        <div class="align-text-center">
                            <img src="~/img/tutorial/shopify-tutorial/choose-app-and-sale.png" class="sync-tutorial-img" />
                        </div>
                        <p><b>Step 3:</b> Choose <i>Develop apps</i></p>
                        <div class="align-text-center">
                            <img src="~/img/tutorial/shopify-tutorial/choose-develope-app.png" class="sync-tutorial-img" />
                        </div>
                        <p><b>Step 4:</b> Click on <i>Create an app</i> button</p>
                        <div class="align-text-center">
                            <img src="~/img/tutorial/shopify-tutorial/click-create-an-app.png" class="sync-tutorial-img" />
                        </div>
                        <p><b>Step 5:</b> Fill in required fields and create app</p>
                        <div class="align-text-center">
                            <img src="~/img/tutorial/shopify-tutorial/create-app.png" class="sync-tutorial-img" />
                        </div>
                        <p><b>Step 6:</b> Choose <i>Configure Admin API scope</i></p>
                        <div class="align-text-center">
                            <img src="~/img/tutorial/shopify-tutorial/config-scope.png" class="sync-tutorial-img" />
                        </div>
                        <p><b>Step 7:</b> Allow below access scopes</p>
                        <div class="align-text-center">
                            <img src="~/img/tutorial/shopify-tutorial/scope-list.png" class="sync-tutorial-img" />
                        </div>
                        <p><b>Step 8:</b> Install your app</p>
                        <div class="align-text-center">
                            <img src="~/img/tutorial/shopify-tutorial/install-app.png" class="sync-tutorial-img" />
                        </div>
                        <p><b>Step 9:</b> Retrieve access token</p>
                        <div class="align-text-center">
                            <img src="~/img/tutorial/shopify-tutorial/get-access-token.png" class="sync-tutorial-img" />
                        </div>
                        <p><b>Step 10:</b> Retrieve your shop domain</p>
                        <div class="align-text-center">
                            <img src="~/img/tutorial/shopify-tutorial/get-shop-domain.png" class="sync-tutorial-img" />
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="save-shopify-setting">Save changes</button>
                </div>
            </div>
        </div>
    </div>
</main>

@section Script {
    <script>
        $(document).ready(function() {
            getEcommerceToken();
        })

        $('#save-haravan-setting').click(function() {
            var currentWebsite = ''
            var haravanToken = $('#haravan-access-token').val();
            if (!haravanToken) {
                toastr_call('error', 'Error', 'Haravan access token could not be blank!');
            }
            else {
                saveAccessToken(haravanToken, '@Common.Constant.DataSource.HARAVAN', null, '@Common.Constant.CookiesName.CURRENT_WEBSITE');
            }
        })

        $('#save-shopify-setting').click(function() {
            var shopifyToken = $('#shopify-access-token').val();
            var shopifyShopDomain = $('#shopify-shop-domain').val();
            if (!shopifyShopDomain || !shopifyToken) {
                toastr_call('error', 'Error', 'Shopify access token and shop domain could not be blank!');
            }
            else {
                saveAccessToken(shopifyToken, '@Common.Constant.DataSource.SHOPIFY', shopifyShopDomain, '@Common.Constant.CookiesName.CURRENT_WEBSITE');
            }
        })

        function saveAccessToken(token, dataSource, shopDomain, currentWebsite) {
            $('.loading').css('display', 'block');
            var websiteId = localStorage.getItem(currentWebsite);
            $.ajax({
                url: `@Url.Action("SaveAccessToken", "DataSynchronization")`,
                type: 'post',
                data: {
                    token: token,
                    dataSource: dataSource,
                    shopDomain: shopDomain,
                    websiteId: websiteId
                },
                success: (result) => {
                    $('.loading').css('display', 'none');
                    if (!result.isSuccessful) {
                        toastr_call('error', 'Error', result.message);
                    }
                    else {
                        toastr_call('success', 'Success', 'Update successfully!');
                    }
                }
            })
        }

        function getEcommerceToken() {
            $.ajax({
                url: `@Url.Action("GetWebsiteById", "DataSynchronization")?id=${localStorage.getItem('@Common.Constant.CookiesName.CURRENT_WEBSITE')}`,
                type: 'get',
                success: (result) => {
                    if (result == null) return;
                    if (result.shopifyToken) {
                        $('#shopify-access-token').val(result.shopifyToken);
                    }
                    else {
                        $('#shopify-access-token').val('');
                    }
                    if (result.shopifyStore) {
                        $('#shopify-shop-domain').val(result.shopifyStore);
                    }
                    else {
                        $('#shopify-shop-domain').val('');
                    }
                    if (result.haravanToken) {
                        $('#haravan-access-token').val(result.haravanToken);
                    }
                    else {
                        $('#haravan-access-token').val('');
                    }
                }
            })
        }

        $('#choose-websites').change(function () {
            getEcommerceToken();
        })
        
    </script>
}